name: Daily AI News to Discord

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  post-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run news poster
        env:
          DISCORD_WEBHOOK:    ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN:       ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY:  ${{ github.repository }}
        run: python news_fetcher.py
